### ISSUE TITLE
tags with the same slug error

### ISSUE THREAD

**Issue by tasomaniac** [bebraw/blogger2ghost#11]
The tool really works great. It worked for me except for one issue that I resolved really easily. 
I had these tags in my blogger: `koç_uni` `koc_uni` and `koç_üni` 
When you generate slugs slugs of these tags are all `koc_uni` without any international UTF-8 chars.
Slugs should be unique and Ghost didn't let me to import the posts. I changed the tags manually and re-imported. 

Thank you.

**Comment by bebraw** [comment]
Good point! This needs to be changed somehow.

Diacritics got tidied in b26041cf . It cleans up the tags on purpose but I can see that can be problematic now.

There a couple of ways to resolve this:

1. Eliminate duplicate tags after conversion step. The gotcha here is that you will lose that UTF-8 information which might not be desirable after all.
2. Push stripping of diacritics behind a feature flag and permit them by default. This would resolve your issue.

What do you think?

**Comment by tasomaniac** [comment]
I already resolved it by removing the tags. Actually in my case they are not that important and the first option would have worked for me.
