### ISSUE TITLE
Bug Trying to export blogger file

### ISSUE THREAD

**Issue by P3lUZa** [bebraw/blogger2ghost#14]
>
/usr/local/lib/node_modules/blogger2ghost/lib/convert.js:50
                html.slice(0, 50) +
                     ^
TypeError: Cannot call method 'slice' of undefined
    at posts (/usr/local/lib/node_modules/blogger2ghost/lib/convert.js:50:22)
    at Array.map (native)
    at module.exports (/usr/local/lib/node_modules/blogger2ghost/lib/convert.js:44:51)
    at runTask (/usr/local/lib/node_modules/blogger2ghost/index.js:52:18)
    at /usr/local/lib/node_modules/blogger2ghost/index.js:44:13
    at /usr/local/lib/node_modules/blogger2ghost/lib/load_json.js:12:9
    at fs.js:272:14
    at Object.oncomplete (fs.js:107:15)

**Comment by bebraw** [comment]
Thanks! The check against missing post title was too early. I moved it to a better place. Please have another go. :+1:

**Comment by P3lUZa** [comment]
A lot better, then this problem was caused because of the "Drafts" (many of them don't have a tittle)

**Comment by bebraw** [comment]
@P3lUZa Great to hear it works now. :+1:

FYI, we've been working on a light alternative for Ghost. Check out [Antwar](https://antwarjs.github.io/). It's completely static and based on React/Webpack. You can host the result easily on GitHub Pages.
