### ISSUE TITLE
Bug importing images: Unnecessary extra line break

### ISSUE THREAD

**Issue by Kikobeats** [bebraw/blogger2ghost#17]
When I imported the data, images have extra line break that makes that markdown render fails:

````
[![](http://url.com)

](http://urlimage.com) 
```

should be:

```
[![](http://url.com)](http://urlimage.com) 
```

**Comment by bebraw** [comment]
Good catch. Want to do a PR?

**Comment by Kikobeats** [comment]
I don't understand the part of the code to fix this :P

**Comment by Kikobeats** [comment]
maybe here?

https://github.com/bebraw/blogger2ghost/blob/master/lib/convert.js#L249

**Comment by bebraw** [comment]
Yeah, that could be it. It would be wise to extract that part to a module of its own and write a test to see if that's the culprit.
