### ISSUE TITLE
Blogger max: 150 posts

### ISSUE THREAD

**Issue by pjking07** [bebraw/blogger2ghost#19]
When trying to create the JSON file, only the first 150 posts are imported from my Blogger site (adoptedbytheking.com). This appears to be related to the Blogger API's max post limit.

Re the blogger JSON: To get to the rest of the posts, I have to modify the JSON url to page through the data.

Perhaps, this tool could automatically page through the Blogger JSON API?

**Comment by markbaird** [comment]
This is actually made worse by a recent change in the Blogger API where it will only return a max of 150 posts at a time. The max used to be 500.

**Comment by pjking07** [comment]
Ah, I couldn't find that documented, but yes, I'm running into that 150 limit.

**Comment by bebraw** [comment]
Do you want to PR a fix? I think it should be fairly easy to paginate using caolan/async or such.

**Comment by pjking07** [comment]
I'd have to learn node first :smile_cat: Can't promise that anytime soon!

**Comment by bebraw** [comment]
No worries. Take your time. I might resolve this if I get some time to work on my personal blog. :+1:
