### ISSUE TITLE
Keep Blogger Permalinks

### ISSUE THREAD

**Issue by pjking07** [bebraw/blogger2ghost#20]
When importing from Blogger to Ghost, the original Blogger permalinks are being lost.
- Blogger url: `/2015/12/green-light.html`
- Expected Ghost url: `/2015/12/green-light.html`
- Actual Ghost url: `/green_light/`

Is it possible to keep the original permalink?

**Comment by bebraw** [comment]
That would be a good fix. If it's not in the Blogger data, you can at least derive it. PR welcome. :)

**Comment by pjking07** [comment]
I'm new to Ghost. Will Ghost allow for a slug (or equivalent) of `/2015/12/green-light.html`?

**Comment by bebraw** [comment]
> I'm new to Ghost. Will Ghost allow for a slug (or equivalent) of /2015/12/green-light.html?

I'm not sure. You would have to ask from Ghost forums for that. Perhaps there's some nice way to set up redirects at least.
