### ISSUE TITLE
Losing content in post

### ISSUE THREAD

**Issue by pjking07** [bebraw/blogger2ghost#21]
During conversion, some content is getting jumbled and lost. 

Source (blogger) post: http://www.adoptedbytheking.com/2015/11/read-in-november.html

**Blogger HTML snippet:**

```
<ul><li>
  <a href="http://www.amazon.com/gp/product/006226835X">
    Yes Please
  </a>
  , by Amy Poehler: I’m a huge <em>Parks and Recreation</em> fan, 
  so I was excited to read Amy’s memoir. It wasn’t my favorite book, 
  but I enjoyed it well enough.
</li></ul>
```

**Expected Ghost Markdown:**

```
* [Yes Please](http://www.amazon.com/gp/product/006226835X), by Amy Poehler: I’m a huge _Parks and Recreation_ fan, so I was excited to read Amy’s memoir. It wasn’t my favorite book, but I enjoyed it well enough.
```

**Actual Ghost Markdown:**

```
* , by Amy Poehler: I’m a huge _Parks and Recreation_[Yes Please](http://www.amazon.com/gp/product/006226835X)
```

**Comment by bebraw** [comment]
That might be a dependency issue. Blogger HTML goes through a certain lib. Maybe you can test against it.

**Comment by pjking07** [comment]
FWIW: Here is the direct blogger JSON

```
\u003C\/p\u003E \u003Cul\u003E \u003Cli\u003E\u003Ca href=\"http:\/\/www.amazon.com\/gp\/product\/006226835X\"\u003EYes Please\u003C\/a\u003E, by Amy Poehler: I’m a huge \u003Cem\u003EParks and Recreation\u003C\/em\u003E fan, so I was excited to read Amy’s memoir. It wasn’t my favorite book, but I enjoyed it well enough.\u003C\/li\u003E
```

**Comment by bebraw** [comment]
Can you try bumping [to-markdown](https://www.npmjs.com/package/to-markdown) to the newest version?

**Comment by pjking07** [comment]
FTR: I've been using the output from http://www.blogger2ghost.com.

Okay, ran locally with `to-markdown` 2.0.1. Same result:

```
* , by Amy Poehler: I’m a huge _Parks and Recreation_[Yes Please](http://www.amazon.com/gp/product/006226835X)
```

**Comment by bebraw** [comment]
@pjking07 Alright. Do you want to post a bug report at _to-markdown_? If you can provide a standalone test case for them to run, that would be great.
