### ISSUE TITLE
Duplicate Entry Found. Multiple values of " found for .

### ISSUE THREAD

**Issue by musicm122** [bebraw/blogger2ghost#23]
Using the site **http://www.blogger2ghost.com/**
I attempted to export from http://archive.hackerferret.com and upload to  http://hkferret.ghost.io

After attempting to upload my file I get this error repeatedly.

> Duplicate Entry Found. Multiple values of " found for .

**Comment by bebraw** [comment]
It might be some corner case we are missing. Could you try running through the cli version and debug further? It would be good to understand why it's empty in this case.

One option would be to discard the other entries it finds. I don't remember what "entry" refers to, but code probably explains it all.

**Comment by musicm122** [comment]
K will give it a try. Thanks for the speedy response!~
